version: "3.8"

services:
  go-app:
    build: .
    environment:
      MONGO_DB: receipt_processor_db
      MONGO_DSN: mongodb://root:password@receipt-processor-api-mongodb-1:27017/?authSource=admin
      SERVER_PORT: 8000
    ports:
      - 8000:8000

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: receipt_processor_db
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: {}
