openapi: 3.0.3
servers:
  - url: "http://localhost:8000"
info:
  title: Receipt Processor
  description: REST API for the receipt processor
  version: 1.0.0
  contact:
    email: eriksostenessimon@gmail.com
paths:
  /api/v1/receipts/process:
    post:
      summary: Submits a receipt for processing
      operationId: addReceipt
      description: Submits a receipt for processing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Receipt"
      responses:
        201:
          description: "Created receipt: returns the ID assigned to the receipt"
          content:
            apllication/json:
              schema:
                type: object
                required:
                  - id
                properties:
                  id:
                    type: string
                    pattern: "^\\S+$"
                    example: adb6b560-0eef-42bc-9d16-df48f30e89b2
        400:
          description: "Invalid receipt: incorrect field values or duplicate receipt"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        422:
          description: The receipt format of the body of the request is malformed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/v1/receipts/{id}/points:
    get:
      summary: Returns the points awarded for the receipt
      description: Returns the points awarded for the receipt
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the receipt
          schema:
            type: string
            pattern: "^\\S+$"
      responses:
        200:
          description: The number of points awarded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Point"
        400:
          description: The receipt id format is incorrect
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: No receipt found for that id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Receipt:
      type: object
      required:
        - retailer
        - purchaseDate
        - purchaseTime
        - items
        - total

      properties:
        id:
          description: The receipt identifier can be sent in the request body or can be generated by the server
          type: string
          pattern: "^\\S+$"
          example: adb6b560-0eef-42bc-9d16-df48f30e89b2
        retailer:
          description: The name of the retailer or store the receipt is from.
          type: string
          pattern: "^\\S+$"
          example: "Target"
        purchaseDate:
          description: The date of the purchase printed on the receipt.
          type: string
          format: date
          example: "2022-01-01"
        purchaseTime:
          description: The time of the purchase printed on the receipt. 24-hour time expected.
          type: string
          format: time
          example: "13:01"
        items:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/Item"
        total:
          description: The total amount paid on the receipt.
          type: string
          pattern: "^\\d+\\.\\d{2}$"
          example: "6.49"

    Item:
      type: object
      required:
        - shortDescription
        - price
      properties:
        shortDescription:
          description: The Short Product Description for the item.
          type: string
          pattern: "^[\\w\\s\\-]+$"
          example: "Mountain Dew 12PK"
        price:
          description: The total price payed for this item.
          type: string
          pattern: "^\\d+\\.\\d{2}$"
          example: "6.49"
    Error:
      type: object
      properties:
        error:
          type: string
          example: "unexpected error"
    Point:
      type: object
      properties:
        points:
          type: integer
          format: uint8
          example: 109
